on:
  workflow_call:
    inputs:
      app_type:
        required: true
        type: string

jobs:
  java:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
