on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_env:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: 'raghudevopsb85/roboshop-helm'
          path: 'helm'
      - name: Deploy
        run: |
          cd helm
          ls -l
          echo ${GITHUB_SHA}

